### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by infogatel2** [rcschaff82/cwp_icecast#2]
I try to start icecast server and there is no change to status 
![icecast_status1](https://user-images.githubusercontent.com/10423259/84835554-8559c280-b03c-11ea-87e6-112a63de2d60.jpg)

**Comment by infogatel2** [comment]
If i press admin panel button i get "ERR_CONNECTION_REFUSED".
I checked firewall and the port is normally open.
Maybe i should play a little with configuration.

**Comment by rcschaff82** [comment]
Please check the /var/log/icecast/error.log

**Comment by infogatel2** [comment]
I just checked it and there is no log created. The folder is empty.

**Comment by rcschaff82** [comment]
please try reinstall from the installer script.  Made some changes.

**Comment by rcschaff82** [comment]
wget -O - https://raw.githubusercontent.com/rcschaff82/cwp_installers/master/cwp_icecast.install | bash

**Comment by infogatel2** [comment]
`Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.net
 * epel: mirror.speedpartner.de
 * extras: mirror.cuegee.com
 * updates: ftp.hosteurope.de
varnishcache_varnish5/x86_64/signature                   |  836 B     00:00
varnishcache_varnish5/x86_64/signature                   | 1.0 kB     00:00 !!!
varnishcache_varnish5-source/signature                   |  836 B     00:00
varnishcache_varnish5-source/signature                   | 1.0 kB     00:00 !!!
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Nothing to do
fatal: destination path 'cwp_icecast' already exists and is not an empty directo                                                                             ry.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.net
 * epel: mirror.speedpartner.de
 * extras: mirror.cuegee.com
 * updates: ftp.wrz.de
Package icecast-2.4.4-1.el7.x86_64 already installed and latest version
Nothing to do
`
Just installed but there was no change. The server status won't change and admin panel is not accesible. I tryied to add ports to UDP too but with no luck.

**Comment by infogatel2** [comment]
When i start server i see the "Starting" and even if i refresh the page there is no change. The same happens if i stop it.
![icecast_status2](https://user-images.githubusercontent.com/10423259/84838703-c1dcec80-b043-11ea-98bd-ea74ab74117a.jpg)

**Comment by rcschaff82** [comment]
what happens if you run 

/usr/bin/icecast -b -c /home/dimradi/8002.conf

as shell

**Comment by infogatel2** [comment]
The result will be as follows. 

```
Starting icecast2
Detaching from the console
[2020-06-17  02:59:11] WARN CONFIG/_parse_root Warning, <location> not configured, using default value "Earth".
[2020-06-17  02:59:11] WARN CONFIG/_parse_root Warning, <admin> contact not configured, using default value "icemaster@localhost".
ERROR: You should not run icecast2 as root
Use the changeowner directive in the config file
```

**Comment by rcschaff82** [comment]
ok.  now try 
killall icecast
sudo -u dimradi /usr/bin/icecast -b -c /home/dimradi/8002.conf

**Comment by infogatel2** [comment]
Sorry but i was away from office.
I just tested 
Result for killall icecast is 
`icecast: no process found
`
and the command 
sudo -u dimradi /usr/bin/icecast -b -c /home/dimradi/8002.conf 
gives again

` [2020-06-17  17:11:24] WARN CONFIG/_parse_root Warning, <location> not configured, using default value "Earth".
[2020-06-17  17:11:24] WARN CONFIG/_parse_root Warning, <admin> contact not configured, using default value "icemaster@localhost". FATAL: could not open error logging (/var/log/icecast/error.log): Permission denied FATAL: could not open access logging (/var/log/icecast/access.log): Permission denied FATAL: Could not start logging
`

**Comment by rcschaff82** [comment]
Not sure why, but the icecast folder was not created when the server was added as it should have been.  Please do an update and remove and recreate the icecast servers.

**Comment by infogatel2** [comment]
Hello and thank you for your efford.
I deleted all the created servers.
I just unistalled totally the module.
I reinstalled, updated and tested once again.
I get the same above errors and when i start the server and run killall icecast i get that no process found.
Did you managed to test and confirm the normall operation?
I use 0.9.8.991 CWP version.

**Comment by rcschaff82** [comment]
I have successfully tested it on 3 servers.  Can you do a "ls -al" or home/dimradi/
